# Server and project configuration
sonar.host.url=https://sonar.wpengine.io/
sonar.projectVersion=1.0-beta
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

# Project identifiers
sonar.projectName=base-images-public
sonar.projectKey=wpengine_base-images-public_28b2728e-ae21-4512-ae17-20ed7584dd99

# Individual configurations
# e.g., go, java, js, php

# sonar.language=python

# Paths to source code directories (use relative paths)

# sonar.sources=cmd, pkg

# Additional parameters for advanced configurations
# Common exclusion patterns

# sonar.exclusions=**/*_test.*, **/mocks/**, **/node_modules/**

# Paths to test code directories (use relative paths)

# sonar.tests=.

# Adjust for your language

# sonar.test.inclusions=**/*_test.go

# Coverage report configuration
# sonar.coverage.exclusions=
# sonar.go.coverage.reportPaths=coverage.out
# example path for javascript and lcov coverage report: sonar.javascript.lcov.reportPaths=coverage/lcov.info