# Builds a docker image with the requirementes for triggering the site-responses on kubernetes
From google/cloud-sdk

RUN apt-get update && apt-get install -y \
  make \
  python-pip

RUN pip install jinja2
