on:
  # Trigger analysis for pushes and pull requests
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube
jobs:
  ie_deploy_quality_gate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history for better SCM information
          fetch-depth: 0

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.23.0"

      # If necessary, include additional steps, such as installing dependencies.

      # - name: Run Tests
      #   env:
      # Add test environment variables if needed
      #   TEST_ENV_VAR1: value1
      #   TEST_ENV_VAR2: value2
      # run: |
      # # Replace with your command which run tests and generates coverage report, e.g., `make test`
      #   <test_command>

      # - name: Upload Coverage Report
      #   uses: actions/upload-artifact@v4
      # with:
      #   name: coverage-report
      #   path: coverage.out
      # Adjust to the path of your coverage report (name has to be the same as in sonar-project.properties file)

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # add these secrets to GitHub
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}